In [1]:
import numpy as np

In [12]:
arr = np.array([2,4,5,0,6,1,5,4,1,-3])

In [13]:
np.min(arr)

-3

In [14]:
np.max(arr)

6

In [15]:
np.mean(arr)

2.5

In [16]:
np.median(arr)

3.0

In [17]:
np.std(arr)

2.6551836094703507

In [18]:
np.absolute(arr)

array([2, 4, 5, 0, 6, 1, 5, 4, 1, 3])

In [19]:
np.abs(arr)

array([2, 4, 5, 0, 6, 1, 5, 4, 1, 3])

In [21]:
np.cumsum(arr)

array([ 2,  6, 11, 11, 17, 18, 23, 27, 28, 25])

In [22]:
np.unique(arr)

array([-3,  0,  1,  2,  4,  5,  6])

In [23]:
np.exp(arr)

array([7.38905610e+00, 5.45981500e+01, 1.48413159e+02, 1.00000000e+00,
       4.03428793e+02, 2.71828183e+00, 1.48413159e+02, 5.45981500e+01,
       2.71828183e+00, 4.97870684e-02])

In [24]:
np.info(np.prod)

 prod(a, axis=None, dtype=None, out=None, keepdims=<no value>,
      initial=<no value>, where=<no value>)

Return the product of array elements over a given axis.

Parameters
----------
a : array_like
    Input data.
axis : None or int or tuple of ints, optional
    Axis or axes along which a product is performed.  The default,
    axis=None, will calculate the product of all the elements in the
    input array. If axis is negative it counts from the last to the
    first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a product is performed on all of the
    axes specified in the tuple instead of a single axis or all the
    axes as before.
dtype : dtype, optional
    The type of the returned array, as well as of the accumulator in
    which the elements are multiplied.  The dtype of `a` is used by
    default unless `a` has an integer dtype of less precision than the
    default platform integer.  In that case, if `a` is signed then the
    platform integer is us

In [25]:
np.prod(arr)

0

In [26]:
for x in arr:
    print(x)

2
4
5
0
6
1
5
4
1
-3


In [27]:
np.info(np.nditer)

 nditer()

nditer(op, flags=None, op_flags=None, op_dtypes=None, order='K', casting='safe', op_axes=None, itershape=None, buffersize=0)

Efficient multi-dimensional iterator object to iterate over arrays.
To get started using this object, see the
:ref:`introductory guide to array iteration <arrays.nditer>`.

Parameters
----------
op : ndarray or sequence of array_like
    The array(s) to iterate over.

flags : sequence of str, optional
      Flags to control the behavior of the iterator.

      * ``buffered`` enables buffering when required.
      * ``c_index`` causes a C-order index to be tracked.
      * ``f_index`` causes a Fortran-order index to be tracked.
      * ``multi_index`` causes a multi-index, or a tuple of indices
        with one per iteration dimension, to be tracked.
      * ``common_dtype`` causes all the operands to be converted to
        a common data type, with copying or buffering as necessary.
      * ``copy_if_overlap`` causes the iterator to determine if read


In [28]:
np.info(np.ndenumerate)

 ndenumerate(arr)

Multidimensional index iterator.

Return an iterator yielding pairs of array coordinates and values.

Parameters
----------
arr : ndarray
  Input array.

See Also
--------
ndindex, flatiter

Examples
--------
>>> a = np.array([[1, 2], [3, 4]])
>>> for index, x in np.ndenumerate(a):
...     print(index, x)
(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [29]:
np.info(np.where)

 where()

where(condition, [x, y], /)

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes
-----
If all the arrays are 1-D, `where` is equivalent to::

    [xv if c else yv
     for c, xv, yv in zip(condition, x, y)]

Examples

In [30]:
np.where(arr == 1)

(array([5, 8]),)

In [31]:
np.where(arr > 5)

(array([4]),)

In [32]:
arr

array([ 2,  4,  5,  0,  6,  1,  5,  4,  1, -3])

In [33]:
arr[arr>1]

array([2, 4, 5, 6, 5, 4])

In [35]:
a2 = np.array([[1, 2, 3, 7, 8, 9], [4, 5, 5, 10, 11, 12]])

In [36]:
splitted = np.array_split(arr, 3, axis=0)
splitted

[array([2, 4, 5, 0]), array([6, 1, 5]), array([ 4,  1, -3])]

In [37]:
splitted = np.array_split(a2, 2, axis=0)
splitted

[array([[1, 2, 3, 7, 8, 9]]), array([[ 4,  5,  5, 10, 11, 12]])]

In [38]:
arr5 = np.array([1, 2, np.nan, 7, 4, 0])
print(arr5)
sum(arr5)

[ 1.  2. nan  7.  4.  0.]


nan

In [40]:
for x in arr5:
    if np.isnan(x):
        x = 0
print(arr5)

[ 1.  2. nan  7.  4.  0.]


In [42]:

for pos in range(len(arr5)):
    if np.isnan(arr5[pos]):
        arr5[pos] = 0

print(arr5)

[1. 2. 0. 7. 4. 0.]


In [45]:
lista = [x/2 for x in arr5]
lista

[0.5, 1.0, 0.0, 3.5, 2.0, 0.0]

In [47]:
arr6 = np.array([1, 2, np.nan, 7, 4, 0])
lista = [x for x in arr6 if not np.isnan(x)]
np.array(lista)

array([1., 2., 7., 4., 0.])

In [49]:
np.isnan(arr6)

array([False, False,  True, False, False, False])

In [50]:
arr6[np.logical_not(np.isnan(arr6))]

array([1., 2., 7., 4., 0.])

In [51]:
arr6[np.isfinite(arr6)]

array([1., 2., 7., 4., 0.])

In [53]:
copia = arr6.copy()
vista = arr6.view()

print('original:', arr6)
print('copia:', copia)
print('vista:', vista)

arr6[0] = 67

print('original:', arr6)
print('copia:', copia)
print('vista:', vista)

original: [ 1.  2. nan  7.  4.  0.]
copia: [ 1.  2. nan  7.  4.  0.]
vista: [ 1.  2. nan  7.  4.  0.]
original: [67.  2. nan  7.  4.  0.]
copia: [ 1.  2. nan  7.  4.  0.]
vista: [67.  2. nan  7.  4.  0.]


In [54]:
arr6.dtype

dtype('float64')

In [56]:
vista = arr6.view(dtype=np.int32)
print('vista:', vista)

vista: [         0 1079033856          0 1073741824          0 2146959360
          0 1075576832          0 1074790400          0          0]


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr2 = arr.reshape([2,3,2])
print(arr2)
arro =arr2.reshape(12)
arro

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1, 1], [2, 2, 2]])

print(a+b)
print(a*b)

[[2 3 4]
 [6 7 8]]
[[ 1  2  3]
 [ 8 10 12]]


In [15]:
a = np.array([[1, 2], [4, 5]])
b = np.array([[1, 1], [2, 2]])

print(a*b)

[[ 1  2]
 [ 8 10]]


In [16]:
print(a.trace)

<built-in method trace of numpy.ndarray object at 0x7f0260203390>


In [17]:
np.linalg.det(a)

-2.9999999999999996

In [18]:
# 1x + 2y =1
# 3x + 5y =2
a = np.array([[1,2],[3,5]])
b = np.array([1,2])

np.linalg.solve(a, b)

array([-1.,  1.])

In [33]:
# Ejercicio 1 Numpy
a1 = np.arange(6)
print(a1)
a2 = np.random.random([3,2])
print(a2)
a3 = np.random.random([2,3,4])
print(a3)

[0 1 2 3 4 5]
[[0.51068182 0.91040166]
 [0.18543696 0.92708277]
 [0.8126674  0.28367843]]
[[[0.81867951 0.4017331  0.05020101 0.31550064]
  [0.32518728 0.420432   0.06474643 0.65477107]
  [0.81887814 0.08826631 0.18302087 0.60291007]]

 [[0.85742552 0.11408707 0.89060045 0.2477898 ]
  [0.72134827 0.20521991 0.47679796 0.37078686]
  [0.03628567 0.19003454 0.79124889 0.08273923]]]


In [34]:
print(a1.ndim)

1


In [46]:
#Ejercicio 2

def funcion_est(array):

    if array.ndim == 1:

        estadis = {
        'quantiles': np.quantile(array),
        'mediana': np.median(array),
        'media': np.mean(array),
        'varianza': np.var(array),
        'desviacion_estandar': np.std(array),
        'minimo': np.min(array),
        'maximo': np.max(array),
        }
    
        return estadis
    else:
        return 'No es de una dimension'

funcion_est(a1)



{'cuadrado': array([ 1.,  2.,  4.,  8., 16., 32.]),
 'mediana': 2.5,
 'media': 2.5,
 'varianza': 2.9166666666666665,
 'desviacion_estandar': 1.707825127659933,
 'minimo': 0,
 'maximo': 5}

In [49]:
#Ejercicio 3
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15],[16, 17, 18]], [[19, 20, 21],[22, 23, 24]] ])
arr


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [ ]:
arr[-1, -1, -1] '24'

In [ ]:
arr[0,1,:]