In [1]:
import numpy as np

In [2]:
arr = np.array([2,4,5,0,6,1,5,4,1,-3])

In [3]:
np.min(arr)

-3

In [4]:
np.max(arr)

6

In [5]:
np.mean(arr)

2.5

In [6]:
np.median(arr)

3.0

In [7]:
np.std(arr)

2.6551836094703507

In [8]:
np.absolute(arr)

array([2, 4, 5, 0, 6, 1, 5, 4, 1, 3])

In [9]:
np.abs(arr)

array([2, 4, 5, 0, 6, 1, 5, 4, 1, 3])

In [10]:
np.cumsum(arr)

array([ 2,  6, 11, 11, 17, 18, 23, 27, 28, 25])

In [11]:
np.unique(arr)

array([-3,  0,  1,  2,  4,  5,  6])

In [12]:
np.exp(arr)

array([7.38905610e+00, 5.45981500e+01, 1.48413159e+02, 1.00000000e+00,
       4.03428793e+02, 2.71828183e+00, 1.48413159e+02, 5.45981500e+01,
       2.71828183e+00, 4.97870684e-02])

In [13]:
np.info(np.prod)

 prod(a, axis=None, dtype=None, out=None, keepdims=<no value>,
      initial=<no value>, where=<no value>)

Return the product of array elements over a given axis.

Parameters
----------
a : array_like
    Input data.
axis : None or int or tuple of ints, optional
    Axis or axes along which a product is performed.  The default,
    axis=None, will calculate the product of all the elements in the
    input array. If axis is negative it counts from the last to the
    first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a product is performed on all of the
    axes specified in the tuple instead of a single axis or all the
    axes as before.
dtype : dtype, optional
    The type of the returned array, as well as of the accumulator in
    which the elements are multiplied.  The dtype of `a` is used by
    default unless `a` has an integer dtype of less precision than the
    default platform integer.  In that case, if `a` is signed then the
    platform integer is us

In [14]:
np.prod(arr)

0

In [15]:
for x in arr:
    print(x)

2
4
5
0
6
1
5
4
1
-3


In [16]:
np.info(np.nditer)

 nditer()

nditer(op, flags=None, op_flags=None, op_dtypes=None, order='K', casting='safe', op_axes=None, itershape=None, buffersize=0)

Efficient multi-dimensional iterator object to iterate over arrays.
To get started using this object, see the
:ref:`introductory guide to array iteration <arrays.nditer>`.

Parameters
----------
op : ndarray or sequence of array_like
    The array(s) to iterate over.

flags : sequence of str, optional
      Flags to control the behavior of the iterator.

      * ``buffered`` enables buffering when required.
      * ``c_index`` causes a C-order index to be tracked.
      * ``f_index`` causes a Fortran-order index to be tracked.
      * ``multi_index`` causes a multi-index, or a tuple of indices
        with one per iteration dimension, to be tracked.
      * ``common_dtype`` causes all the operands to be converted to
        a common data type, with copying or buffering as necessary.
      * ``copy_if_overlap`` causes the iterator to determine if read


In [17]:
np.info(np.ndenumerate)

 ndenumerate(arr)

Multidimensional index iterator.

Return an iterator yielding pairs of array coordinates and values.

Parameters
----------
arr : ndarray
  Input array.

See Also
--------
ndindex, flatiter

Examples
--------
>>> a = np.array([[1, 2], [3, 4]])
>>> for index, x in np.ndenumerate(a):
...     print(index, x)
(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [18]:
np.info(np.where)

 where()

where(condition, [x, y], /)

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes
-----
If all the arrays are 1-D, `where` is equivalent to::

    [xv if c else yv
     for c, xv, yv in zip(condition, x, y)]

Examples

In [19]:
np.where(arr == 1)

(array([5, 8]),)

In [20]:
np.where(arr > 5)

(array([4]),)

In [21]:
arr

array([ 2,  4,  5,  0,  6,  1,  5,  4,  1, -3])

In [22]:
arr[arr>1]

array([2, 4, 5, 6, 5, 4])

In [23]:
a2 = np.array([[1, 2, 3, 7, 8, 9], [4, 5, 5, 10, 11, 12]])

In [24]:
splitted = np.array_split(arr, 3, axis=0)
splitted

[array([2, 4, 5, 0]), array([6, 1, 5]), array([ 4,  1, -3])]

In [25]:
splitted = np.array_split(a2, 2, axis=0)
splitted

[array([[1, 2, 3, 7, 8, 9]]), array([[ 4,  5,  5, 10, 11, 12]])]

In [26]:
arr5 = np.array([1, 2, np.nan, 7, 4, 0])
print(arr5)
sum(arr5)

[ 1.  2. nan  7.  4.  0.]


nan

In [27]:
for x in arr5:
    if np.isnan(x):
        x = 0
print(arr5)

[ 1.  2. nan  7.  4.  0.]


In [28]:

for pos in range(len(arr5)):
    if np.isnan(arr5[pos]):
        arr5[pos] = 0

print(arr5)

[1. 2. 0. 7. 4. 0.]


In [29]:
lista = [x/2 for x in arr5]
lista

[0.5, 1.0, 0.0, 3.5, 2.0, 0.0]

In [30]:
arr6 = np.array([1, 2, np.nan, 7, 4, 0])
lista = [x for x in arr6 if not np.isnan(x)]
np.array(lista)

array([1., 2., 7., 4., 0.])

In [31]:
np.isnan(arr6)

array([False, False,  True, False, False, False])

In [32]:
arr6[np.logical_not(np.isnan(arr6))]

array([1., 2., 7., 4., 0.])

In [33]:
arr6[np.isfinite(arr6)]

array([1., 2., 7., 4., 0.])

In [34]:
copia = arr6.copy()
vista = arr6.view()

print('original:', arr6)
print('copia:', copia)
print('vista:', vista)

arr6[0] = 67

print('original:', arr6)
print('copia:', copia)
print('vista:', vista)

original: [ 1.  2. nan  7.  4.  0.]
copia: [ 1.  2. nan  7.  4.  0.]
vista: [ 1.  2. nan  7.  4.  0.]
original: [67.  2. nan  7.  4.  0.]
copia: [ 1.  2. nan  7.  4.  0.]
vista: [67.  2. nan  7.  4.  0.]


In [35]:
arr6.dtype

dtype('float64')

In [36]:
vista = arr6.view(dtype=np.int32)
print('vista:', vista)

vista: [         0 1079033856          0 1073741824          0 2146959360
          0 1075576832          0 1074790400          0          0]


In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr2 = arr.reshape([2,3,2])
print(arr2)
arro =arr2.reshape(12)
arro

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [38]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1, 1], [2, 2, 2]])

print(a+b)
print(a*b)

[[2 3 4]
 [6 7 8]]
[[ 1  2  3]
 [ 8 10 12]]


In [39]:
a = np.array([[1, 2], [4, 5]])
b = np.array([[1, 1], [2, 2]])

print(a*b)

[[ 1  2]
 [ 8 10]]


In [40]:
print(a.trace)

<built-in method trace of numpy.ndarray object at 0x7f7ec2f76d90>


In [41]:
np.linalg.det(a)

-2.9999999999999996

In [42]:
# 1x + 2y =1
# 3x + 5y =2
a = np.array([[1,2],[3,5]])
b = np.array([1,2])

np.linalg.solve(a, b)

array([-1.,  1.])

In [43]:
# Ejercicio 1 Numpy
a1 = np.arange(6)
print(a1)
a2 = np.random.random([3,2])
print(a2)
a3 = np.random.random([2,3,4])
print(a3)

[0 1 2 3 4 5]
[[0.09626622 0.01584993]
 [0.28594345 0.7861468 ]
 [0.45931727 0.20921485]]
[[[0.46861951 0.13610876 0.90121442 0.31974569]
  [0.61955505 0.17633189 0.63927017 0.16691762]
  [0.55820009 0.0460982  0.54225881 0.30255626]]

 [[0.63117444 0.49648186 0.9946968  0.05775935]
  [0.92372439 0.8228938  0.14527231 0.42902757]
  [0.8996204  0.38993898 0.94557873 0.61004702]]]


In [44]:
print(a1.ndim)

1


In [48]:
#Ejercicio 2

def funcion_est(array):

    if array.ndim == 1:

        estadis = {
        'q1': np.percentile(array,25),
        'q2': np.percentile(array,50),
        'q3': np.percentile(array,75),
        'mediana': np.median(array),
        'media': np.mean(array),
        'varianza': np.var(array),
        'desviacion_estandar': np.std(array),
        'minimo': np.min(array),
        'maximo': np.max(array),
        }
    
        return estadis
    else:
        return 'No es de una dimension'

funcion_est(a1)



{'q1': 1.25,
 'q2': 2.5,
 'q3': 3.75,
 'mediana': 2.5,
 'media': 2.5,
 'varianza': 2.9166666666666665,
 'desviacion_estandar': 1.707825127659933,
 'minimo': 0,
 'maximo': 5}

In [49]:
#Ejercicio 3
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15],[16, 17, 18]], [[19, 20, 21],[22, 23, 24]] ])
arr
#

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [51]:
arr[-1, -1, -1] 
'24'

'24'

In [ ]:
arr[0,1,:]
'4, 5, 6'

In [52]:
arr[:,0,:]
'1, 2, 3'
print(arr[:,0,:])

[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]
 [19 20 21]]


In [53]:
arr[:,:,-1]
print(arr[:,:,-1])

[[ 3  6]
 [ 9 12]
 [15 18]
 [21 24]]


In [54]:
arr[1,2,3]
print(arr[1,2,3])

IndexError: index 2 is out of bounds for axis 1 with size 2

In [55]:
arr[2,1,0]
print(arr[2,1,0])

16


In [56]:
arr[::2,:,:]
print(arr[::2,:,:])

[[[ 1  2  3]
  [ 4  5  6]]

 [[13 14 15]
  [16 17 18]]]


In [59]:
#Ejercicio 4
'Crea un array de 3 x 3 que contenga valores aleatorios entre el 0 y el 100. Tendrás que usar el submódulo random. Una vez tengas el código, transfórmalo a una función que te permita crear arrays de tamaño N x N'

np.random.random([3,3])*100

array([[96.21285063, 46.18825161, 75.70414005],
       [14.09662023, 46.41781872, 47.90769569],
       [60.93333818, 37.35361844, 13.65661289]])

In [63]:
'Ejercicio 5'
'Crea una función que dependa de un número. Si la función se ejecuta con el número 5, debe devolver el siguiente array'
'1 1 1 1 1'
'1 0 0 0 1'
'1 0 0 0 1'
'1 0 0 0 1'
'1 1 1 1 1'

aone = np.ones([5,5])
print(aone)
acero = np.zeros([3,3])
print(acero)

aone[1:4,1:4] = 0

print(aone)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
def gen_cuadrado_1_0(n):
    ones

In [66]:
' Ejercicio 6 Crea una función que te detecte las dimensiones de un array, y te diga cuántos datos faltantes contiene. Crea unos datos de ejemplo para comprobarlo'
arr1 = np.ones([3,3])
arr1[1,1] = np.nan
arr1[2,0] = np.nan
arr1

array([[ 1.,  1.,  1.],
       [ 1., nan,  1.],
       [nan,  1.,  1.]])

In [64]:
'Ejercicio7 Crea una fución que te calcule los márgenes de una tabla, es decir, la suma por columnas, la suma por filas y el total. Idealmente, añadelo a la tabla original'

arr = np.array([[3,2,1,2], [6,7,9,5]])
arr

array([[3, 2, 1, 2],
       [6, 7, 9, 5]])

In [72]:
help(np.hstack)
help(np.vstack)

Help on function hstack in module numpy:

hstack(tup)
    Stack arrays in sequence horizontally (column wise).
    
    This is equivalent to concatenation along the second axis, except for 1-D
    arrays where it concatenates along the first axis. Rebuilds arrays divided
    by `hsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the second axis,
        except 1-D arrays which can be any length.
    
    Returns
    -------
    stacked : ndarray
        The array formed by stacking the given arrays.
    
    See Also
    --------
    concatenate : Join a sequence of arrays along an existing axis.
    s

In [85]:
sum_fil = (np.sum(arr, axis=1)).reshape(-1,1)
sum_col = (np.sum(arr, axis=0))
total = np.sum(arr)

#print(sum_fil)
#print(sum_col)
#print(total)

tabla_filas = np.hstack((arr,sum_fil))
ultima_fila = np.hstack([sum_col, total])
tabla_margenes = np.vstack((tabla_filas, ultima_fila))
print(tabla_margenes)


[[ 3  2  1  2  8]
 [ 6  7  9  5 27]
 [ 9  9 10  7 35]]


In [86]:
def gen_tabla_margenes(array):
    sum_fil = (np.sum(array, axis=1)).reshape(-1,1)
    sum_col = (np.sum(array, axis=0))
    total = np.sum(array)
    tabla_filas = np.hstack((array,sum_fil))
    ultima_fila = np.hstack([sum_col, total])
    tabla_margenes = np.vstack((tabla_filas, ultima_fila))

    return(tabla_margenes)

gen_tabla_margenes(arr)

array([[ 3,  2,  1,  2,  8],
       [ 6,  7,  9,  5, 27],
       [ 9,  9, 10,  7, 35]])

In [ ]:
'Ejercicio 8'
'Crea una función que dados dos arrays X e Y, te calcule el coeficiente de correlación entre ellos usando la siguiente fórmula'

'https://wikimedia.org/api/rest_v1/media/math/render/svg/2b9c2079a3ffc1aacd36201ea0a3fb2460dc226f'

x = np.array([2,3,4,6,7,8,9,7])
y = np.array([5,6,8,5,10,8,9,5])

In [89]:
x = np.array([2,3,4,6,7,8,9,7])
y = np.array([5,6,8,5,10,8,9,5])

media_x = np.mean(x)
media_y = np.mean(y)

In [90]:
numerador = np.sum((x-media_x)*(y-media_y))

In [92]:
denominador = np.sqrt(np.sum((x-media_x)**2))*np.sqrt(np.sum((y-media_y)**2))

In [93]:
corr = numerador/denominador
corr

0.5157614295551275

In [ ]:
def coef_corr(x,y):
  
   media_x = np.mean(x)
   media_y = np.mean(y)
   numerador = np.sum((x-media_x)*(y-media_y))
   denominador = np.sqrt(np.sum((x-media_x)**2))*np.sqrt(np.sum((y-media_y)**2))

   if denominador == 0:
    return 'Error, denominador 0'

   corr = numerador/denominador

   return corr