In [11]:
import numpy as np

In [12]:
arr = np.array([2,4,5,0,6,1,5,4,1,-3])

In [13]:
np.min(arr)

-3

In [14]:
np.max(arr)

6

In [15]:
np.mean(arr)

2.5

In [16]:
np.median(arr)

3.0

In [17]:
np.std(arr)

2.6551836094703507

In [18]:
np.absolute(arr)

array([2, 4, 5, 0, 6, 1, 5, 4, 1, 3])

In [19]:
np.abs(arr)

array([2, 4, 5, 0, 6, 1, 5, 4, 1, 3])

In [21]:
np.cumsum(arr)

array([ 2,  6, 11, 11, 17, 18, 23, 27, 28, 25])

In [22]:
np.unique(arr)

array([-3,  0,  1,  2,  4,  5,  6])

In [23]:
np.exp(arr)

array([7.38905610e+00, 5.45981500e+01, 1.48413159e+02, 1.00000000e+00,
       4.03428793e+02, 2.71828183e+00, 1.48413159e+02, 5.45981500e+01,
       2.71828183e+00, 4.97870684e-02])

In [24]:
np.info(np.prod)

 prod(a, axis=None, dtype=None, out=None, keepdims=<no value>,
      initial=<no value>, where=<no value>)

Return the product of array elements over a given axis.

Parameters
----------
a : array_like
    Input data.
axis : None or int or tuple of ints, optional
    Axis or axes along which a product is performed.  The default,
    axis=None, will calculate the product of all the elements in the
    input array. If axis is negative it counts from the last to the
    first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a product is performed on all of the
    axes specified in the tuple instead of a single axis or all the
    axes as before.
dtype : dtype, optional
    The type of the returned array, as well as of the accumulator in
    which the elements are multiplied.  The dtype of `a` is used by
    default unless `a` has an integer dtype of less precision than the
    default platform integer.  In that case, if `a` is signed then the
    platform integer is us

In [25]:
np.prod(arr)

0

In [26]:
for x in arr:
    print(x)

2
4
5
0
6
1
5
4
1
-3


In [27]:
np.info(np.nditer)

 nditer()

nditer(op, flags=None, op_flags=None, op_dtypes=None, order='K', casting='safe', op_axes=None, itershape=None, buffersize=0)

Efficient multi-dimensional iterator object to iterate over arrays.
To get started using this object, see the
:ref:`introductory guide to array iteration <arrays.nditer>`.

Parameters
----------
op : ndarray or sequence of array_like
    The array(s) to iterate over.

flags : sequence of str, optional
      Flags to control the behavior of the iterator.

      * ``buffered`` enables buffering when required.
      * ``c_index`` causes a C-order index to be tracked.
      * ``f_index`` causes a Fortran-order index to be tracked.
      * ``multi_index`` causes a multi-index, or a tuple of indices
        with one per iteration dimension, to be tracked.
      * ``common_dtype`` causes all the operands to be converted to
        a common data type, with copying or buffering as necessary.
      * ``copy_if_overlap`` causes the iterator to determine if read


In [28]:
np.info(np.ndenumerate)

 ndenumerate(arr)

Multidimensional index iterator.

Return an iterator yielding pairs of array coordinates and values.

Parameters
----------
arr : ndarray
  Input array.

See Also
--------
ndindex, flatiter

Examples
--------
>>> a = np.array([[1, 2], [3, 4]])
>>> for index, x in np.ndenumerate(a):
...     print(index, x)
(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [29]:
np.info(np.where)

 where()

where(condition, [x, y], /)

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes
-----
If all the arrays are 1-D, `where` is equivalent to::

    [xv if c else yv
     for c, xv, yv in zip(condition, x, y)]

Examples

In [30]:
np.where(arr == 1)

(array([5, 8]),)

In [31]:
np.where(arr > 5)

(array([4]),)

In [32]:
arr

array([ 2,  4,  5,  0,  6,  1,  5,  4,  1, -3])

In [33]:
arr[arr>1]

array([2, 4, 5, 6, 5, 4])

In [35]:
a2 = np.array([[1, 2, 3, 7, 8, 9], [4, 5, 5, 10, 11, 12]])

In [36]:
splitted = np.array_split(arr, 3, axis=0)
splitted

[array([2, 4, 5, 0]), array([6, 1, 5]), array([ 4,  1, -3])]

In [37]:
splitted = np.array_split(a2, 2, axis=0)
splitted

[array([[1, 2, 3, 7, 8, 9]]), array([[ 4,  5,  5, 10, 11, 12]])]

In [38]:
arr5 = np.array([1, 2, np.nan, 7, 4, 0])
print(arr5)
sum(arr5)

[ 1.  2. nan  7.  4.  0.]


nan

In [40]:
for x in arr5:
    if np.isnan(x):
        x = 0
print(arr5)

[ 1.  2. nan  7.  4.  0.]


In [42]:

for pos in range(len(arr5)):
    if np.isnan(arr5[pos]):
        arr5[pos] = 0

print(arr5)

[1. 2. 0. 7. 4. 0.]


In [45]:
lista = [x/2 for x in arr5]
lista

[0.5, 1.0, 0.0, 3.5, 2.0, 0.0]

In [47]:
arr6 = np.array([1, 2, np.nan, 7, 4, 0])
lista = [x for x in arr6 if not np.isnan(x)]
np.array(lista)

array([1., 2., 7., 4., 0.])

In [49]:
np.isnan(arr6)

array([False, False,  True, False, False, False])

In [50]:
arr6[np.logical_not(np.isnan(arr6))]

array([1., 2., 7., 4., 0.])

In [51]:
arr6[np.isfinite(arr6)]

array([1., 2., 7., 4., 0.])

In [53]:
copia = arr6.copy()
vista = arr6.view()

print('original:', arr6)
print('copia:', copia)
print('vista:', vista)

arr6[0] = 67

print('original:', arr6)
print('copia:', copia)
print('vista:', vista)

original: [ 1.  2. nan  7.  4.  0.]
copia: [ 1.  2. nan  7.  4.  0.]
vista: [ 1.  2. nan  7.  4.  0.]
original: [67.  2. nan  7.  4.  0.]
copia: [ 1.  2. nan  7.  4.  0.]
vista: [67.  2. nan  7.  4.  0.]


In [54]:
arr6.dtype

dtype('float64')

In [56]:
vista = arr6.view(dtype=np.int32)
print('vista:', vista)

vista: [         0 1079033856          0 1073741824          0 2146959360
          0 1075576832          0 1074790400          0          0]
